# Generated by Django 3.2.5 on 2022-04-26 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internshipapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='internship',
            name='postdate',
        ),
    ]
