# Generated by Django 3.2.5 on 2022-04-26 05:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('internshipapi', '0002_remove_internship_postdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='date_posted',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
