# Generated by Django 3.2.5 on 2022-04-26 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('internshipapi', '0003_internship_date_posted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internship',
            old_name='date_posted',
            new_name='postdate',
        ),
    ]
